version: '3.9'

services:
  tor:
    security_opt:
      - seccomp:unconfined    
    shm_size: 1024g
    build:
      context: ./
      dockerfile: tor.Dockerfile
      args:
        FOO: FOO
    environment:
      SGX: -1
    volumes:
      - ./network/:/network
      - ./network-torpy/:/network-torpy
      # - ./torpy/torpy/:/usr/local/lib/python3.8/dist-packages/torpy